###
POST http://localhost:8080/logout

### 어드민 계정정보 atreus/1234 (id = 4)

### 어드민이 비정상 충전코드 발급을 시도한다. : 금 만기일이 충전코드 만기일보다 앞설 때
POST http://localhost:8080/admin/redeemcodes
Authorization: Basic YXRyZXVzOjEyMzQ=
Content-Type: application/json

{
  "amount": 10000,
  "goldExpiredBy": "2022-12-15T10:15:30+01:00",
  "codeExpiredBy": "2022-12-31T10:15:30+01:00"
}

### 어드민이 비정상 충전코드 발급을 시도한다. : 만기일이 현재보다 이전일 때
POST http://localhost:8080/admin/redeemcodes
Authorization: Basic YXRyZXVzOjEyMzQ=
Content-Type: application/json

{
  "amount": 10000,
  "goldExpiredBy": "2021-12-15T10:15:30+01:00",
  "codeExpiredBy": "2021-12-31T10:15:30+01:00"
}
